#!/bin/bash

defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 2
defaults write com.apple.dock static-only -bool true
defaults write com.apple.gamed Disabled -bool true
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false


killall Dock
